apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - rag-pvc.yaml
  - ml-deployment.yaml
  - ml-service.yaml
  - ml-hpa.yaml
  - rag-deployment.yaml
  - rag-service.yaml
  - agent-deployment.yaml
  - agent-service.yaml
  - ingress.yaml

commonLabels:
  project: telco-churn
  managed-by: kustomize
