apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: churn-ml-hpa
  namespace: mlops
  labels:
    app: churn-ml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: churn-ml-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120    # Wait 2 min before scaling down
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0      # Scale up immediately
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30
