apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-pvc
  namespace: mlops
  labels:
    app: churn-rag
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard   # uncomment and set for specific cloud storage class
